[Clang][MinGW] Export nested classes which instantiated by enclosing template's explicit instantiation declaration
MinGW-GCC applies explicit instantiateion declaration of a class template to its nested type but doesn't inherit
`__declspec(dllexport)` attribute to the nested class, causes undefined reference to member functions of the nested
class.
To resolve this self-inconsistency, such `__declspec(dllexport)` attribute on explicit instantiation declaration should
inherit to the nested class.